# 1. Create a 3x3x3 array with random values

In [16]:
import numpy as np
arr = np.random.random((3,3,3))
arr

array([[[0.11464097, 0.01031546, 0.5796065 ],
        [0.7578803 , 0.0869631 , 0.40751146],
        [0.63918212, 0.98287814, 0.16525665]],

       [[0.45336049, 0.06977065, 0.66801388],
        [0.7778922 , 0.60220728, 0.93365477],
        [0.74020423, 0.68272787, 0.05184567]],

       [[0.79163066, 0.53705708, 0.47549503],
        [0.12321621, 0.66942683, 0.65940108],
        [0.15196946, 0.09756714, 0.65634273]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
arr = np.diag([1,2,3,4],-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
arr = np.zeros((8,8),dtype=int)
arr[::2,1::2]=1
arr[1::2,::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [21]:
arr= np.random.random((5,5))
print("Original Array:")
print(arr)
arrmax, arrmin = arr.max(), arr.min()
norm_arr = (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
print(norm_arr)

Original Array:
[[0.19523112 0.53168807 0.83241368 0.69038571 0.07734392]
 [0.17303259 0.25229655 0.11030952 0.74664334 0.39489523]
 [0.58245043 0.94803884 0.20837288 0.87222229 0.32248118]
 [0.24262407 0.42508803 0.52716441 0.40643307 0.4811405 ]
 [0.35593603 0.50992336 0.18526463 0.13346483 0.31417086]]
After normalization:
[[0.13539439 0.52181785 0.86720359 0.70408335 0.        ]
 [0.10989919 0.20093448 0.03786126 0.76869569 0.3647102 ]
 [0.58011882 1.         0.15048781 0.9129241  0.28154208]
 [0.18982557 0.39938686 0.51662239 0.37796149 0.46376356]
 [0.31996524 0.49682091 0.12394779 0.06445531 0.27199762]]


# 5. How to find common values between two arrays?

In [19]:
arr1=[4,6,2,3,8]
print("Array 1 : ", arr1)
arr2=[1,5,4,7,6,8]
print("Array 2 : ", arr2)
print("Common Values between two arrays : ", np.intersect1d(arr1,arr2))

Array 1 :  [4, 6, 2, 3, 8]
Array 2 :  [1, 5, 4, 7, 6, 8]
Common Values between two arrays :  [4 6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
today = np.datetime64('today')
yesterday=np.datetime64(today)-np.timedelta64(1)
print("Yesterday : ",yesterday)
print("Today : ",today)
tommorow = np.datetime64(today)+np.timedelta64(1)
print("Tommorow : ",tommorow)

Yesterday :  2020-07-30
Today :  2020-07-31
Tommorow :  2020-08-01


# 7. Consider two random array A and B, check if they are equal

In [7]:
arrA=np.random.randint(0,5,5)
print("Array 1 : ", arrA)
arrB=np.random.randint(0,5,5)
print("Array 2 : ", arrB)
result = np.array_equal(arrA,arrB)
result

Array 1 :  [1 4 1 2 2]
Array 2 :  [3 4 3 3 3]


False

# 8.Create random vector of size 10 and replace the maximum value by 0

In [18]:
arr=np.random.random(10)
print(arr)
arr[arr.argmax()]=0
print(arr)

[0.46333586 0.61634346 0.66701817 0.89576145 0.8921684  0.07575509
 0.03316856 0.48967148 0.62999656 0.1881955 ]
[0.46333586 0.61634346 0.66701817 0.         0.8921684  0.07575509
 0.03316856 0.48967148 0.62999656 0.1881955 ]


# 9. How to print all the values of an array?

In [9]:
arr=np.empty((10),dtype=int)
print(arr)

[ -998670336       32760 -1017990544       32760           0           0
           0           0          14           1]


# 10.Subtract the mean of each row of a matrix

In [10]:
arr = np.random.rand(2, 4)
print("Original matrix:\n",arr)
res_arr = arr - arr.mean(axis=1, keepdims=True)
print("\nSubtract the mean of each row of the original matrix:\n",res_arr)

Original matrix:
 [[0.79291452 0.33207059 0.61137689 0.91866609]
 [0.0432153  0.33830915 0.08127918 0.44369191]]

Subtract the mean of each row of the original matrix:
 [[ 0.1291575  -0.33168644 -0.05238013  0.25490907]
 [-0.18340859  0.11168527 -0.1453447   0.21706802]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
import numpy as np
arr = np.random.randint(0, 10, 5)
print(arr)
arr1 = [1,2,3]
arr[arr1] +=1
print(arr)

[2 9 4 9 8]
[ 2 10  5 10  8]


# 12.How to get the diagonal of a dot product?

In [12]:
first_arr = np.random.randint(0,10,(3,3))
print("First Array : \n",first_arr)
second_arr= np.random.randint(0,10,(3,3))
print("Second Array : \n",second_arr)
dot_product = np.dot(first_arr, second_arr)
Diag_result=np.diag(dot_product)
print("diagonal of a dot product : \n",Diag_result)

First Array : 
 [[9 4 4]
 [2 7 0]
 [0 3 5]]
Second Array : 
 [[7 4 6]
 [2 4 9]
 [1 3 4]]
diagonal of a dot product : 
 [75 36 47]


# 13.How to find the most frequent value in an array?

In [13]:
arr = np.random.randint(0, 10, 40)
print("Original array:\n",arr)
res = np.bincount(arr).argmax()
print("Most frequent value in the above array : ",res)

Original array:
 [0 9 1 7 4 2 0 6 6 0 9 9 1 5 9 2 1 3 0 7 7 8 9 8 9 1 5 2 9 7 0 9 4 3 8 6 6
 4 0 7]
Most frequent value in the above array :  9


# 14.How to get the n largest values of an array

In [14]:
arr = np.arange(10)
np.random.shuffle(arr)
print("Original array:",arr)
n = 3
res = arr[np.argsort(arr)[-n:]]
print("Largest n values of an array : ",res)

Original array: [9 1 4 2 6 5 3 0 7 8]
Largest n values of an array :  [7 8 9]


# 15.How to create a record array from a regular array?

In [15]:
arr1=np.array([8,3,6,2])
arr2=np.array(['Black','Blue','White','Red'])
arr3=np.array([10,20,30,40])
result= np.core.records.fromarrays([arr1, arr2, arr3],names='a,b,c')
result

rec.array([(8, 'Black', 10), (3, 'Blue', 20), (6, 'White', 30),
           (2, 'Red', 40)],
          dtype=[('a', '<i4'), ('b', '<U5'), ('c', '<i4')])